package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private int idAlmacen;
     private String nombreAlmacen;
     private String direccion;
     private Double capacidad;
     private Set<Seccion> seccions = new HashSet<Seccion>(0);

    public Almacen() {
    }

	
    public Almacen(int idAlmacen, String nombreAlmacen, String direccion) {
        this.idAlmacen = idAlmacen;
        this.nombreAlmacen = nombreAlmacen;
        this.direccion = direccion;
    }
    public Almacen(int idAlmacen, String nombreAlmacen, String direccion, Double capacidad, Set<Seccion> seccions) {
       this.idAlmacen = idAlmacen;
       this.nombreAlmacen = nombreAlmacen;
       this.direccion = direccion;
       this.capacidad = capacidad;
       this.seccions = seccions;
    }
   
    public int getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(int idAlmacen) {
        this.idAlmacen = idAlmacen;
    }
    public String getNombreAlmacen() {
        return this.nombreAlmacen;
    }
    
    public void setNombreAlmacen(String nombreAlmacen) {
        this.nombreAlmacen = nombreAlmacen;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Double getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Double capacidad) {
        this.capacidad = capacidad;
    }
    public Set<Seccion> getSeccions() {
        return this.seccions;
    }
    
    public void setSeccions(Set<Seccion> seccions) {
        this.seccions = seccions;
    }




}


