package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0



/**
 * Indicacion generated by hbm2java
 */
public class Indicacion  implements java.io.Serializable {


     private int idIndicacion;
     private Preparacion preparacion;
     private int ordenIndicacion;
     private String detalleIndicacion;

    public Indicacion() {
    }

    public Indicacion(int idIndicacion, Preparacion preparacion, int ordenIndicacion, String detalleIndicacion) {
       this.idIndicacion = idIndicacion;
       this.preparacion = preparacion;
       this.ordenIndicacion = ordenIndicacion;
       this.detalleIndicacion = detalleIndicacion;
    }
   
    public int getIdIndicacion() {
        return this.idIndicacion;
    }
    
    public void setIdIndicacion(int idIndicacion) {
        this.idIndicacion = idIndicacion;
    }
    public Preparacion getPreparacion() {
        return this.preparacion;
    }
    
    public void setPreparacion(Preparacion preparacion) {
        this.preparacion = preparacion;
    }
    public int getOrdenIndicacion() {
        return this.ordenIndicacion;
    }
    
    public void setOrdenIndicacion(int ordenIndicacion) {
        this.ordenIndicacion = ordenIndicacion;
    }
    public String getDetalleIndicacion() {
        return this.detalleIndicacion;
    }
    
    public void setDetalleIndicacion(String detalleIndicacion) {
        this.detalleIndicacion = detalleIndicacion;
    }




}


