package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private int idLote;
     private String codigoLote;
     private Double costoLote;
     private double cantidaUnidadesLote;
     private Date fechaCaducacionLote;
     private Set<ProductoSeccion> productoSeccions = new HashSet<ProductoSeccion>(0);

    public Lote() {
    }

	
    public Lote(int idLote, String codigoLote, double cantidaUnidadesLote) {
        this.idLote = idLote;
        this.codigoLote = codigoLote;
        this.cantidaUnidadesLote = cantidaUnidadesLote;
    }
    public Lote(int idLote, String codigoLote, Double costoLote, double cantidaUnidadesLote, Date fechaCaducacionLote, Set<ProductoSeccion> productoSeccions) {
       this.idLote = idLote;
       this.codigoLote = codigoLote;
       this.costoLote = costoLote;
       this.cantidaUnidadesLote = cantidaUnidadesLote;
       this.fechaCaducacionLote = fechaCaducacionLote;
       this.productoSeccions = productoSeccions;
    }
   
    public int getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(int idLote) {
        this.idLote = idLote;
    }
    public String getCodigoLote() {
        return this.codigoLote;
    }
    
    public void setCodigoLote(String codigoLote) {
        this.codigoLote = codigoLote;
    }
    public Double getCostoLote() {
        return this.costoLote;
    }
    
    public void setCostoLote(Double costoLote) {
        this.costoLote = costoLote;
    }
    public double getCantidaUnidadesLote() {
        return this.cantidaUnidadesLote;
    }
    
    public void setCantidaUnidadesLote(double cantidaUnidadesLote) {
        this.cantidaUnidadesLote = cantidaUnidadesLote;
    }
    public Date getFechaCaducacionLote() {
        return this.fechaCaducacionLote;
    }
    
    public void setFechaCaducacionLote(Date fechaCaducacionLote) {
        this.fechaCaducacionLote = fechaCaducacionLote;
    }
    public Set<ProductoSeccion> getProductoSeccions() {
        return this.productoSeccions;
    }
    
    public void setProductoSeccions(Set<ProductoSeccion> productoSeccions) {
        this.productoSeccions = productoSeccions;
    }




}


