package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private TipoPersona tipoPersona;
     private String nombrePersona;
     private String apellidoPaternoPersona;
     private String apellidoMaternoPersona;
     private String documentoIdentidadPersona;
     private String numeroDocumentoPersona;
     private String numeroTelefonoPersona;
     private String correoPersona;
     private String direccionPersona;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Servicio> serviciosForIdPersonaEmpleado = new HashSet<Servicio>(0);
     private Set<Servicio> serviciosForIdPersonaAtendidaServicio = new HashSet<Servicio>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, TipoPersona tipoPersona, String nombrePersona, String documentoIdentidadPersona, String numeroDocumentoPersona, String correoPersona, String direccionPersona) {
        this.idPersona = idPersona;
        this.tipoPersona = tipoPersona;
        this.nombrePersona = nombrePersona;
        this.documentoIdentidadPersona = documentoIdentidadPersona;
        this.numeroDocumentoPersona = numeroDocumentoPersona;
        this.correoPersona = correoPersona;
        this.direccionPersona = direccionPersona;
    }
    public Persona(int idPersona, TipoPersona tipoPersona, String nombrePersona, String apellidoPaternoPersona, String apellidoMaternoPersona, String documentoIdentidadPersona, String numeroDocumentoPersona, String numeroTelefonoPersona, String correoPersona, String direccionPersona, Set<Usuario> usuarios, Set<Servicio> serviciosForIdPersonaEmpleado, Set<Servicio> serviciosForIdPersonaAtendidaServicio) {
       this.idPersona = idPersona;
       this.tipoPersona = tipoPersona;
       this.nombrePersona = nombrePersona;
       this.apellidoPaternoPersona = apellidoPaternoPersona;
       this.apellidoMaternoPersona = apellidoMaternoPersona;
       this.documentoIdentidadPersona = documentoIdentidadPersona;
       this.numeroDocumentoPersona = numeroDocumentoPersona;
       this.numeroTelefonoPersona = numeroTelefonoPersona;
       this.correoPersona = correoPersona;
       this.direccionPersona = direccionPersona;
       this.usuarios = usuarios;
       this.serviciosForIdPersonaEmpleado = serviciosForIdPersonaEmpleado;
       this.serviciosForIdPersonaAtendidaServicio = serviciosForIdPersonaAtendidaServicio;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public TipoPersona getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public String getApellidoPaternoPersona() {
        return this.apellidoPaternoPersona;
    }
    
    public void setApellidoPaternoPersona(String apellidoPaternoPersona) {
        this.apellidoPaternoPersona = apellidoPaternoPersona;
    }
    public String getApellidoMaternoPersona() {
        return this.apellidoMaternoPersona;
    }
    
    public void setApellidoMaternoPersona(String apellidoMaternoPersona) {
        this.apellidoMaternoPersona = apellidoMaternoPersona;
    }
    public String getDocumentoIdentidadPersona() {
        return this.documentoIdentidadPersona;
    }
    
    public void setDocumentoIdentidadPersona(String documentoIdentidadPersona) {
        this.documentoIdentidadPersona = documentoIdentidadPersona;
    }
    public String getNumeroDocumentoPersona() {
        return this.numeroDocumentoPersona;
    }
    
    public void setNumeroDocumentoPersona(String numeroDocumentoPersona) {
        this.numeroDocumentoPersona = numeroDocumentoPersona;
    }
    public String getNumeroTelefonoPersona() {
        return this.numeroTelefonoPersona;
    }
    
    public void setNumeroTelefonoPersona(String numeroTelefonoPersona) {
        this.numeroTelefonoPersona = numeroTelefonoPersona;
    }
    public String getCorreoPersona() {
        return this.correoPersona;
    }
    
    public void setCorreoPersona(String correoPersona) {
        this.correoPersona = correoPersona;
    }
    public String getDireccionPersona() {
        return this.direccionPersona;
    }
    
    public void setDireccionPersona(String direccionPersona) {
        this.direccionPersona = direccionPersona;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Servicio> getServiciosForIdPersonaEmpleado() {
        return this.serviciosForIdPersonaEmpleado;
    }
    
    public void setServiciosForIdPersonaEmpleado(Set<Servicio> serviciosForIdPersonaEmpleado) {
        this.serviciosForIdPersonaEmpleado = serviciosForIdPersonaEmpleado;
    }
    public Set<Servicio> getServiciosForIdPersonaAtendidaServicio() {
        return this.serviciosForIdPersonaAtendidaServicio;
    }
    
    public void setServiciosForIdPersonaAtendidaServicio(Set<Servicio> serviciosForIdPersonaAtendidaServicio) {
        this.serviciosForIdPersonaAtendidaServicio = serviciosForIdPersonaAtendidaServicio;
    }




}


