package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Precio generated by hbm2java
 */
public class Precio  implements java.io.Serializable {


     private int idPrecio;
     private Producto producto;
     private Double unitarioPrecio;
     private Date fechaInicioPrecio;
     private Date fechaFinPrecio;
     private Double mayoriaPrecio;
     private boolean vigentePrecio;
     private Double cantidadMayoriaPrecio;

    public Precio() {
    }

	
    public Precio(int idPrecio, Date fechaInicioPrecio, boolean vigentePrecio) {
        this.idPrecio = idPrecio;
        this.fechaInicioPrecio = fechaInicioPrecio;
        this.vigentePrecio = vigentePrecio;
    }
    public Precio(int idPrecio, Producto producto, Double unitarioPrecio, Date fechaInicioPrecio, Date fechaFinPrecio, Double mayoriaPrecio, boolean vigentePrecio, Double cantidadMayoriaPrecio) {
       this.idPrecio = idPrecio;
       this.producto = producto;
       this.unitarioPrecio = unitarioPrecio;
       this.fechaInicioPrecio = fechaInicioPrecio;
       this.fechaFinPrecio = fechaFinPrecio;
       this.mayoriaPrecio = mayoriaPrecio;
       this.vigentePrecio = vigentePrecio;
       this.cantidadMayoriaPrecio = cantidadMayoriaPrecio;
    }
   
    public int getIdPrecio() {
        return this.idPrecio;
    }
    
    public void setIdPrecio(int idPrecio) {
        this.idPrecio = idPrecio;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Double getUnitarioPrecio() {
        return this.unitarioPrecio;
    }
    
    public void setUnitarioPrecio(Double unitarioPrecio) {
        this.unitarioPrecio = unitarioPrecio;
    }
    public Date getFechaInicioPrecio() {
        return this.fechaInicioPrecio;
    }
    
    public void setFechaInicioPrecio(Date fechaInicioPrecio) {
        this.fechaInicioPrecio = fechaInicioPrecio;
    }
    public Date getFechaFinPrecio() {
        return this.fechaFinPrecio;
    }
    
    public void setFechaFinPrecio(Date fechaFinPrecio) {
        this.fechaFinPrecio = fechaFinPrecio;
    }
    public Double getMayoriaPrecio() {
        return this.mayoriaPrecio;
    }
    
    public void setMayoriaPrecio(Double mayoriaPrecio) {
        this.mayoriaPrecio = mayoriaPrecio;
    }
    public boolean isVigentePrecio() {
        return this.vigentePrecio;
    }
    
    public void setVigentePrecio(boolean vigentePrecio) {
        this.vigentePrecio = vigentePrecio;
    }
    public Double getCantidadMayoriaPrecio() {
        return this.cantidadMayoriaPrecio;
    }
    
    public void setCantidadMayoriaPrecio(Double cantidadMayoriaPrecio) {
        this.cantidadMayoriaPrecio = cantidadMayoriaPrecio;
    }




}


