package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Preparacion generated by hbm2java
 */
public class Preparacion  implements java.io.Serializable {


     private int idPreparacion;
     private Producto producto;
     private String nombrePreparacion;
     private Date fechaCreacionPreparacion;
     private String detalleAdicionalPreparacion;
     private Set<Indicacion> indicacions = new HashSet<Indicacion>(0);

    public Preparacion() {
    }

	
    public Preparacion(int idPreparacion, Producto producto, Date fechaCreacionPreparacion, String detalleAdicionalPreparacion) {
        this.idPreparacion = idPreparacion;
        this.producto = producto;
        this.fechaCreacionPreparacion = fechaCreacionPreparacion;
        this.detalleAdicionalPreparacion = detalleAdicionalPreparacion;
    }
    public Preparacion(int idPreparacion, Producto producto, String nombrePreparacion, Date fechaCreacionPreparacion, String detalleAdicionalPreparacion, Set<Indicacion> indicacions) {
       this.idPreparacion = idPreparacion;
       this.producto = producto;
       this.nombrePreparacion = nombrePreparacion;
       this.fechaCreacionPreparacion = fechaCreacionPreparacion;
       this.detalleAdicionalPreparacion = detalleAdicionalPreparacion;
       this.indicacions = indicacions;
    }
   
    public int getIdPreparacion() {
        return this.idPreparacion;
    }
    
    public void setIdPreparacion(int idPreparacion) {
        this.idPreparacion = idPreparacion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNombrePreparacion() {
        return this.nombrePreparacion;
    }
    
    public void setNombrePreparacion(String nombrePreparacion) {
        this.nombrePreparacion = nombrePreparacion;
    }
    public Date getFechaCreacionPreparacion() {
        return this.fechaCreacionPreparacion;
    }
    
    public void setFechaCreacionPreparacion(Date fechaCreacionPreparacion) {
        this.fechaCreacionPreparacion = fechaCreacionPreparacion;
    }
    public String getDetalleAdicionalPreparacion() {
        return this.detalleAdicionalPreparacion;
    }
    
    public void setDetalleAdicionalPreparacion(String detalleAdicionalPreparacion) {
        this.detalleAdicionalPreparacion = detalleAdicionalPreparacion;
    }
    public Set<Indicacion> getIndicacions() {
        return this.indicacions;
    }
    
    public void setIndicacions(Set<Indicacion> indicacions) {
        this.indicacions = indicacions;
    }




}


