package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private int idSeccion;
     private Almacen almacen;
     private String codigoSeccion;
     private Double capacidadSeccion;
     private String detalle;
     private Set<ProductoSeccion> productoSeccions = new HashSet<ProductoSeccion>(0);

    public Seccion() {
    }

	
    public Seccion(int idSeccion, Almacen almacen, String codigoSeccion) {
        this.idSeccion = idSeccion;
        this.almacen = almacen;
        this.codigoSeccion = codigoSeccion;
    }
    public Seccion(int idSeccion, Almacen almacen, String codigoSeccion, Double capacidadSeccion, String detalle, Set<ProductoSeccion> productoSeccions) {
       this.idSeccion = idSeccion;
       this.almacen = almacen;
       this.codigoSeccion = codigoSeccion;
       this.capacidadSeccion = capacidadSeccion;
       this.detalle = detalle;
       this.productoSeccions = productoSeccions;
    }
   
    public int getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(int idSeccion) {
        this.idSeccion = idSeccion;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public String getCodigoSeccion() {
        return this.codigoSeccion;
    }
    
    public void setCodigoSeccion(String codigoSeccion) {
        this.codigoSeccion = codigoSeccion;
    }
    public Double getCapacidadSeccion() {
        return this.capacidadSeccion;
    }
    
    public void setCapacidadSeccion(Double capacidadSeccion) {
        this.capacidadSeccion = capacidadSeccion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set<ProductoSeccion> getProductoSeccions() {
        return this.productoSeccions;
    }
    
    public void setProductoSeccions(Set<ProductoSeccion> productoSeccions) {
        this.productoSeccions = productoSeccions;
    }




}


