package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0



/**
 * ServicioProducto generated by hbm2java
 */
public class ServicioProducto  implements java.io.Serializable {


     private int idServicioProductoSeccion;
     private Servicio servicio;
     private ProductoSeccion productoSeccion;
     private Double costoTotal;
     private Double cantidadServicioProducto;

    public ServicioProducto() {
    }

	
    public ServicioProducto(int idServicioProductoSeccion, Servicio servicio) {
        this.idServicioProductoSeccion = idServicioProductoSeccion;
        this.servicio = servicio;
    }
    public ServicioProducto(int idServicioProductoSeccion, Servicio servicio, ProductoSeccion productoSeccion, Double costoTotal, Double cantidadServicioProducto) {
       this.idServicioProductoSeccion = idServicioProductoSeccion;
       this.servicio = servicio;
       this.productoSeccion = productoSeccion;
       this.costoTotal = costoTotal;
       this.cantidadServicioProducto = cantidadServicioProducto;
    }
   
    public int getIdServicioProductoSeccion() {
        return this.idServicioProductoSeccion;
    }
    
    public void setIdServicioProductoSeccion(int idServicioProductoSeccion) {
        this.idServicioProductoSeccion = idServicioProductoSeccion;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public ProductoSeccion getProductoSeccion() {
        return this.productoSeccion;
    }
    
    public void setProductoSeccion(ProductoSeccion productoSeccion) {
        this.productoSeccion = productoSeccion;
    }
    public Double getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(Double costoTotal) {
        this.costoTotal = costoTotal;
    }
    public Double getCantidadServicioProducto() {
        return this.cantidadServicioProducto;
    }
    
    public void setCantidadServicioProducto(Double cantidadServicioProducto) {
        this.cantidadServicioProducto = cantidadServicioProducto;
    }




}


