package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idServicio;
     private Persona personaByIdPersonaEmpleado;
     private Persona personaByIdPersonaAtendidaServicio;
     private TipoServicio tipoServicio;
     private Date horaInicioServicio;
     private Date horaFinServicio;
     private Date horaEdicionServicio;
     private Set<ServicioProducto> servicioProductos = new HashSet<ServicioProducto>(0);

    public Servicio() {
    }

	
    public Servicio(int idServicio, Persona personaByIdPersonaAtendidaServicio, TipoServicio tipoServicio, Date horaInicioServicio, Date horaFinServicio) {
        this.idServicio = idServicio;
        this.personaByIdPersonaAtendidaServicio = personaByIdPersonaAtendidaServicio;
        this.tipoServicio = tipoServicio;
        this.horaInicioServicio = horaInicioServicio;
        this.horaFinServicio = horaFinServicio;
    }
    public Servicio(int idServicio, Persona personaByIdPersonaEmpleado, Persona personaByIdPersonaAtendidaServicio, TipoServicio tipoServicio, Date horaInicioServicio, Date horaFinServicio, Date horaEdicionServicio, Set<ServicioProducto> servicioProductos) {
       this.idServicio = idServicio;
       this.personaByIdPersonaEmpleado = personaByIdPersonaEmpleado;
       this.personaByIdPersonaAtendidaServicio = personaByIdPersonaAtendidaServicio;
       this.tipoServicio = tipoServicio;
       this.horaInicioServicio = horaInicioServicio;
       this.horaFinServicio = horaFinServicio;
       this.horaEdicionServicio = horaEdicionServicio;
       this.servicioProductos = servicioProductos;
    }
   
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public Persona getPersonaByIdPersonaEmpleado() {
        return this.personaByIdPersonaEmpleado;
    }
    
    public void setPersonaByIdPersonaEmpleado(Persona personaByIdPersonaEmpleado) {
        this.personaByIdPersonaEmpleado = personaByIdPersonaEmpleado;
    }
    public Persona getPersonaByIdPersonaAtendidaServicio() {
        return this.personaByIdPersonaAtendidaServicio;
    }
    
    public void setPersonaByIdPersonaAtendidaServicio(Persona personaByIdPersonaAtendidaServicio) {
        this.personaByIdPersonaAtendidaServicio = personaByIdPersonaAtendidaServicio;
    }
    public TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }
    public Date getHoraInicioServicio() {
        return this.horaInicioServicio;
    }
    
    public void setHoraInicioServicio(Date horaInicioServicio) {
        this.horaInicioServicio = horaInicioServicio;
    }
    public Date getHoraFinServicio() {
        return this.horaFinServicio;
    }
    
    public void setHoraFinServicio(Date horaFinServicio) {
        this.horaFinServicio = horaFinServicio;
    }
    public Date getHoraEdicionServicio() {
        return this.horaEdicionServicio;
    }
    
    public void setHoraEdicionServicio(Date horaEdicionServicio) {
        this.horaEdicionServicio = horaEdicionServicio;
    }
    public Set<ServicioProducto> getServicioProductos() {
        return this.servicioProductos;
    }
    
    public void setServicioProductos(Set<ServicioProducto> servicioProductos) {
        this.servicioProductos = servicioProductos;
    }




}


