package Entities;
// Generated 01-may-2018 23:13:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoServicio generated by hbm2java
 */
public class TipoServicio  implements java.io.Serializable {


     private int idTipoServicio;
     private String nombreTipoServicio;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public TipoServicio() {
    }

	
    public TipoServicio(int idTipoServicio, String nombreTipoServicio) {
        this.idTipoServicio = idTipoServicio;
        this.nombreTipoServicio = nombreTipoServicio;
    }
    public TipoServicio(int idTipoServicio, String nombreTipoServicio, Set<Servicio> servicios) {
       this.idTipoServicio = idTipoServicio;
       this.nombreTipoServicio = nombreTipoServicio;
       this.servicios = servicios;
    }
   
    public int getIdTipoServicio() {
        return this.idTipoServicio;
    }
    
    public void setIdTipoServicio(int idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }
    public String getNombreTipoServicio() {
        return this.nombreTipoServicio;
    }
    
    public void setNombreTipoServicio(String nombreTipoServicio) {
        this.nombreTipoServicio = nombreTipoServicio;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


